<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Reports</title><%@ include file="../common/wholemart-shell-start.jsp" %>
<h1 class="wm-title">Reports</h1><p class="wm-subtitle">View order, payment, and distributor performance reports</p><div class="wm-toolbar"><div class="row g-4"><div class="col-auto"><label>From:</label><input class="wm-input" type="date"></div><div class="col-auto"><label>To:</label><input class="wm-input" type="date"></div><div class="col-auto"><button class="btn wm-gradient-btn" type="button">Export PDF</button></div></div></div><div class="row g-4"><div class="col-lg-6"><section class="wm-section"><h2 class="h5 wm-card-title">Order Summary</h2><p>Total Orders: <strong id="totalOrders">0</strong></p><p>Placed: <strong id="placedOrders">0</strong></p><p>Delivered: <strong id="deliveredOrders">0</strong></p></section></div><div class="col-lg-6"><section class="wm-section"><h2 class="h5 wm-card-title">Payment Summary</h2><p>Total Paid: <strong id="totalPaid">Rs. 0.00</strong></p><p>Ledger Due: <strong id="ledgerDue">Rs. 0.00</strong></p><div class="wm-map">Live payment and ledger totals loaded from database.</div></section></div></div>
<script>
document.addEventListener("DOMContentLoaded", function () {
    function text(id, value) { var element = document.getElementById(id); if (element) element.textContent = value; }
    function money(value) { return "Rs. " + Number(value || 0).toFixed(2); }
    fetch("/api/v1/orders").then(function (response) { return response.json(); }).then(function (data) { var rows = wmRows(data); text("totalOrders", rows.length); text("placedOrders", rows.filter(function (row) { return row.status === "PLACED"; }).length); text("deliveredOrders", rows.filter(function (row) { return row.status === "DELIVERED"; }).length); });
    fetch("/api/v1/payments").then(function (response) { return response.json(); }).then(function (data) { var rows = wmRows(data); text("totalPaid", money(rows.filter(function (row) { return row.status === "PAID"; }).reduce(function (sum, row) { return sum + Number(row.amount || 0); }, 0))); });
    fetch("/api/v1/ledger").then(function (response) { return response.json(); }).then(function (data) { var rows = wmRows(data); text("ledgerDue", money(rows.reduce(function (sum, row) { return sum + Number(row.amount || 0); }, 0))); });
});
</script>
<%@ include file="../common/wholemart-shell-end.jsp" %>
