spring.application.name=localb2b-ai-marketplace

spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false

#spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.url=${DB_URL:jdbc:postgresql://ep-proud-block-ahctzakb.c-3.us-east-1.aws.neon.tech:5432/neondb}
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_fsNFdUa31jCS}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

spring.ai.retry.max-attempts=${SPRING_AI_RETRY_MAX_ATTEMPTS:1}
spring.ai.retry.backoff.initial-interval=${SPRING_AI_RETRY_INITIAL_INTERVAL:250ms}
spring.ai.retry.backoff.max-interval=${SPRING_AI_RETRY_MAX_INTERVAL:1s}
spring.ai.model.chat=${SPRING_AI_MODEL_CHAT:openai}
spring.ai.openai.base-url=${GROQ_BASE_URL:https://api.groq.com/openai}
spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=${GROQ_CHAT_MODEL:llama-3.1-8b-instant}
spring.ai.openai.chat.options.temperature=0.5
spring.ai.openai.chat.options.max-tokens=${GROQ_MAX_TOKENS:180}
spring.ai.openai.chat.options.parallel-tool-calls=false

server.port=${SERVER_PORT:8080}
server.servlet.jsp.init-parameters.development=true
server.servlet.jsp.init-parameters.recompileOnFail=true

localb2b.auth.jwt-secret=${JWT_SECRET:dev-secret-change-me-dev-secret-change-me}
localb2b.auth.access-token-minutes=60
localb2b.auth.refresh-token-days=14

management.endpoints.web.exposure.include=health,info,metrics

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
