package com.localb2b.marketplace.ai.entity;

public enum AiActionType {
    ADD_TO_CART,
    PLACE_ORDER,
    CANCEL_ORDER,
    MAKE_PAYMENT,
    ACCEPT_ORDER,
    REJECT_ORDER,
    ASSIGN_DRIVER,
    UPDATE_DELIVERY_STATUS,
    APPROVE_DISTRIBUTOR,
    APPROVE_DRIVER,
    REFUND_PAYMENT,
    LEDGER_ADJUSTMENT
}
